app.py
from flask import render_template
from flask import Flask
from os import urandom
from blueprints import authentication, apiroutes
from dotenv import load_dotenv


# Initialize the app with random secret_key
app = Flask(__name__)
app.secret_key = urandom(12)

# Load Environment Variables
load_dotenv()

# Add Blueprints
app.register_blueprint(authentication.auth)
app.register_blueprint(apiroutes.api)


@app.route("/")
def index():
    return render_template("index.html")


@app.errorhandler(Exception)
def exception_handler(error):
    return render_template('error-pages/error.html', code=error.code,
                           name=error.name, message=error.description), 404


if __name__ == '__main__':
    app.run(debug=False)

blueprints/apiroutes.py
from flask import Blueprint, jsonify, request
from blueprints.api.rest import GitHubRepo
import asyncio
from json import loads

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)

api = Blueprint('api', __name__)


@api.route('/github', methods=["GET", "POST"])
def github():
    if request.method == 'GET':
        URL = "https://github.com/esp8266/arduino"
    else:
        URL = loads(request.data).get("url", None)
        if URL is None:
            return jsonify(
                {
                    "error": "Please pass a URL in your POST request"
                }
            )
    myrepo = GitHubRepo(url=URL, loop=loop)
    
    return jsonify(myrepo.stats())

blueprints/authentication.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import login_user, logout_user, login_required, UserMixin, current_user
from .backend.database import AuthenticationStore
from os import getenv
from flask_login import LoginManager
from secrets import compare_digest
from .bot.botpanel import BotStats
# Load Environment Variables
from dotenv import load_dotenv
load_dotenv()

auth = Blueprint('auth', __name__)
stat = BotStats()

login_manager = LoginManager()


@auth.record_once
def on_load(state):
    login_manager.init_app(state.app)


@login_manager.user_loader
def load_user(username):
    user = User()
    if db.redis.exists(username):
        user.id = username
    return user


db = AuthenticationStore(host=getenv('HOST'), port=17489, password=getenv('PASSWORD'))


class User(UserMixin):
    pass


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('auth.dashboard'))
    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']
        password_repeat = request.form['password2']
        if not compare_digest(password, password_repeat):
            return
        if db.redis.exists(username):
            return
        db.create_user(user=username, password=password)
        return redirect(url_for('auth.login'))
    return render_template('login/signup.html')


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "GET":
        return render_template("index.html")
    if current_user.is_authenticated:
        return redirect(url_for('auth.dashboard'))
    if request.method == "POST":
        username = request.form['username']
        if not db.redis.exists(username):
            flash("Username does not exist")
            return redirect(url_for('auth.login'))
        if db.validate_hex(user=username, password=request.form.get('password')):
            user = User()
            user.id = username
            login_user(user)
            return redirect(url_for('auth.dashboard'))
        else:
            flash("Password is incorrect")
            return redirect(url_for('auth.login'))


@auth.route('/dashboard')
@login_required
def dashboard():
    return render_template('login/dashboard.html', username=current_user.id), 200


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))


@auth.route('/stats')
@login_required
def stats():
    return render_template('bot/bot.html', stats=stat.get_stats())


@auth.route('/usage')
@login_required
def usage():
    return render_template('usage/usage.html')


@auth.route('/webhook', methods=['POST'])
@login_required
def webhook():
    print(request.form)
    message = request.form['message']
    stat.send_webhook(message)
    return '', 204


@auth.route('/logs')
@login_required
def logs():
    return render_template('logs/terminal.html')

templates/bot/bot.html
<html>
<head>
      <link rel="stylesheet" type="text/css" href="/static/bot/bot.css">
</head>
  <body>
<div id="demo">
  <div class="discord-app-mount">
    <div class="discord-app">
      <div class="app-buttons"></div>
      <div class="guilds">
        <div class="guild selected" style="background-image: url(https://i.ibb.co/F436qJX/ambu-bot.png);"></div>
        <div class="guild"></div>
        <div class="guild guild-add"></div>
      </div>
      <div class="channels">
        <div class="header">Bot Statistics</div>
        <div class="channel-wrapper"></div>
        <h4>#Guild Count: {{stats['guild_count']}}</h4>
        <h4>#Member Count: {{stats['member_count']}}</h4>
        <div class="user"></div>
      </div>
      <div class="chat">
        <div class="header">general</div>
        <div class="messages-wrapper">
           <form action="{{ url_for('auth.webhook') }}", method="post", onsubmit="document.getElementsByClassName(">
            <div class="wrap1">
              <div class="search">

                <input name="message" type="text" class="searchTerm" placeholder="Send a webhook">
                <button type="submit" class="searchButton">
                POST
                </button>
              </div>
            </div>
            </form>
          <div class="messages"></div>
        </div>
        <div class="input-wrapper">
          <div class="input">
            <textarea placeholder="Message #general" disabled="disabled"></textarea>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  </body>
</html>

templates/error-pages/error.html
<!DOCTYPE html>
<html style="height:100%">
        <head><title> {{code}} {{name}}</title>
        </head>
        <body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
                <div style="height:auto; min-height:100%; ">
                        <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
                                <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">{{code}}</h1>
                                <h2 style="margin-top:20px;font-size: 30px;line-height:40px"> {{message}} </h2>
                        </div>
                </div>
        </body>
</html>

templates/index.html
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">

<head>
  <title>Website</title>
  <script src="{{url_for('static', filename='index/index.js')}}"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="/static/index/index.css">
  <link rel="icon" type="image/png" href="https://i.ibb.co/rMXCDQM/android-chrome-192x192-1.png" />
</head>

<body>

  <section class="menu menu--circle">
    <input type="checkbox" id="menu__active" />
    <label for="menu__active" class="menu__active">
      <div class="menu__toggle">
        <div class="icon">
          <div class="hamburger"></div>
        </div>
      </div>
      <input type="radio" name="arrow--up" id="degree--up-0" />
      <input type="radio" name="arrow--up" id="degree--up-1" />
      <input type="radio" name="arrow--up" id="degree--up-2" />
      <div class="menu__listings">
        <ul class="circle">
          <li>
            <div class="placeholder">
              <div class="upside">
                <a href="https://gitlab.com/blacksmithop/website" class="button"><i class="fa fa-gitlab"></i></a>
              </div>
            </div>
          </li>
          <li>
            <div class="placeholder">
              <div class="upside">
                <a onclick="openForm()" class="button"><i class="fa fa-sign-in"></i></a>
              </div>
            </div>
          </li>

          <li>
            <div class="placeholder">
              <div class="upside">
                <a href="https://codepen.io/blacksmithop/pen/gOgWLGg" class="button"><i class="fa fa-codepen"></i></a>
              </div>
            </div>
          </li>
        </ul>
      </div>

  </section>

  <div class="header">

    <!--Content before waves-->
    <div class="inner-header flex">
      <!--Just the logo.. Don't mind this-->
      <svg version="1.1" class="logo" baseProfile="tiny" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 500 500" xml:space="preserve">
        <path fill="#FFFFFF" stroke="#000000" stroke-width="10" stroke-miterlimit="10" d="M57,283" />
        <g>
          <path fill="#fff" d="M250.4,0.8C112.7,0.8,1,112.4,1,250.2c0,137.7,111.7,249.4,249.4,249.4c137.7,0,249.4-111.7,249.4-249.4
C499.8,112.4,388.1,0.8,250.4,0.8z M383.8,326.3c-62,0-101.4-14.1-117.6-46.3c-17.1-34.1-2.3-75.4,13.2-104.1
c-22.4,3-38.4,9.2-47.8,18.3c-11.2,10.9-13.6,26.7-16.3,45c-3.1,20.8-6.6,44.4-25.3,62.4c-19.8,19.1-51.6,26.9-100.2,24.6l1.8-39.7		c35.9,1.6,59.7-2.9,70.8-13.6c8.9-8.6,11.1-22.9,13.5-39.6c6.3-42,14.8-99.4,141.4-99.4h41L333,166c-12.6,16-45.4,68.2-31.2,96.2	c9.2,18.3,41.5,25.6,91.2,24.2l1.1,39.8C390.5,326.2,387.1,326.3,383.8,326.3z" />
        </g>
      </svg>
      <h1>Website</h1>
    </div>

    <!--Waves Container-->
    <div>
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="parallax">
          <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
          <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
        </g>
      </svg>
    </div>
    <!--Waves end-->

  </div>
  <!--Header ends-->

  <!--Form starts-->
<div class="form-popup" id="myForm">
  <form action="{{ url_for('auth.login') }}" method="post" class="form-container">
    <input type="text" placeholder="Username" name="username" required>

    <input type="password" placeholder="Password" name="password" required>

    <button type="submit" class="btn">Login</button>
    <button type="button" class="close fa fa-times" onclick="closeForm()"></button>
  </form>
</div>
  <!--Form ends-->

  <!--Content starts-->
  <div class="content flex">
    <p>BlackSmithOP | 2021 | Free to use</p>
  </div>
  <!--Content ends-->

    </body>

</html>

templates/login/dashboard.html
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="/static/dashboard/dashboard.css">
</head>

<body>
  <!--/ My brand
-->
  <div class="brand">
    <a href="https://www.jamiecoulter.co.uk" target="_blank">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/logo.png" />
    </a>
  </div>
  <!--/ Begin Body
-->
  <div class="swanky">
    <!--/ Introduction Block
  -->
    <div class="swanky_title">
      <h1>Welcome back {{username}}</h1>
      <p>What would you like to do today?</p>

      <div class="swanky_title__social">
        <a href="https://twitter.com/AbhinavKM_" target="_blank">
          <div class="slide">
            <div class="arrow">
              <div class="stem"></div>
              <div class="point"></div>
            </div>
          </div>
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/tw.png" />
          Twitter
        </a>
      </div>
      <div class="swanky_title__social">
        <a href="https://codepen.io/blacksmithop" target="_blank">
          <div class="slide">
            <div class="arrow">
              <div class="stem"></div>
              <div class="point"></div>
            </div>
          </div>
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/cp.png" />
          Codepen
        </a>
      </div>
    </div>
    <!--/////////// Begin Dropdown ////////////
  -->
    <div class="swanky_wrapper">
      <input id="Dashboard" name="radio" type="radio"></input>
      <label for="Dashboard">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/dash.png" />
        <span>Dashboard</span>
        <div class="lil_arrow"></div>
        <div class="bar"></div>
        <div class="swanky_wrapper__content">
          <ul>
            <li><a href="/stats">Bot</a></li>
            <a href="/usage"><li>Usage</li></a>
            <a href="/logs"><li>Logs</li></a>
            <li>Code Blocks</li>
          </ul>
        </div>
      </label>
      <input id="Sales" name="radio" type="radio"></input>
      <label for="Sales">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/del.png" />
        <span>Sales</span>
        <div class="lil_arrow"></div>
        <div class="bar"></div>
        <div class="swanky_wrapper__content">
          <ul>
            <li>New Sales</li>
            <li>Expired Sales</li>
            <li>Sales Reports</li>
            <li>Deliveries</li>
          </ul>
        </div>
      </label>
      <input id="Messages" name="radio" type="radio"></input>
      <label for="Messages">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/mess.png" />
        <span>Messages</span>
        <div class="lil_arrow"></div>
        <div class="bar"></div>
        <div class="swanky_wrapper__content">
          <ul>
            <li>Inbox</li>
            <li>Outbox</li>
            <li>Sent</li>
            <li>Archived</li>
          </ul>
        </div>
      </label>
      <input id="Users" name="radio" type="radio"></input>
      <label for="Users">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/users.png" />
        <span>Users</span>
        <div class="lil_arrow"></div>
        <div class="bar"></div>
        <div class="swanky_wrapper__content">
          <ul>
            <li>New User</li>
            <li>User Groups</li>
            <li>Permissions</li>
            <li>Passwords</li>
          </ul>
        </div>
      </label>
      <input id="Settings" radio="radio" type="radio"></input>
      <label for="Settings">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/set.png" />
        <span>Settings</span>
        <div class="lil_arrow"></div>
        <div class="swanky_wrapper__content">
          <ul>
            <li>Databases</li>
            <li>Design</li>
            <li>Change User</li>
            <li><a href="/logout">Log Out</a></li>
          </ul>
        </div>
      </label>
    </div>
    <!--/////////// End Dropdown ////////////
  -->
  </div>
  <!--/ My Footer
-->
  <div class="love">
    <p>Remixed with <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/love_copy.png" /> by <a href='https://blacksmithop.xyz/' target='_blank'> BlackSmithOP </a></p>
  </div>

</body>

</html>

templates/login/signup.html
     <link rel="stylesheet" type="text/css" href="/static/signup/signup.css">
     <script type="text/javascript"
         src="{{ url_for('static', filename='signup/signup.js') }}"></script>
  <h1>Sign Up</h1>
  <form action="{{ url_for('auth.signup') }}" method="post">
    <input name="username" type="text" autocomplete="off" id="username">
    <label for="username">Username</label>
    <input name="password"type="password" autocomplete="off" id="password">
    <label for="password">Password</label>
    <input name="password2" type="password" id="password2">
    <label for="password">Repeat Password</label>
    <input type="submit" value="Submit" id="submit">

templates/logs/terminal.html
<html>
<head>
      <link rel="stylesheet" type="text/css" href="/static/logs/terminal.css">
</head>
  <body>
    <div class="window">
      <div class="bar">
        <div class="btn"></div>
      </div>
      <div class="body">
        <span class="command">$ echo hi</span><br>
        <span class="command">$ echo hi</span><br>
      </div>
    </div>
  </body>
</html>

templates/usage/usage.html
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Status</title>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.js'></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css" href="/static/usage/usage.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js">
  </script>
  <script src="{{url_for('static', filename='usage/usage.js')}}">
  </script>
</head>
<body>
 <!-- Animated SVG Gauges -->

  <!--
    Gauge: > Network Load
  -->
  <svg id="gaugeLoad" percent="0">
    <circle cx="120" cy="120" r="64"></circle>
    <circle cx="120" cy="120" r="64"></circle>

    <text class="value" x="120" y="130" text-anchor="middle">
      <tspan>0%</tspan>
    </text>

    <text class="caption" x="120" y="220" text-anchor="middle">
      <tspan>Network Load</tspan>
    </text>
  </svg>

  <!--
    Gauge: > CPU Usage
  -->
  <svg id="gaugeCPU" percent="0">
    <circle cx="120" cy="120" r="64"></circle>
    <circle cx="120" cy="120" r="64"></circle>

    <text class="value" x="120" y="130" text-anchor="middle">
      <tspan>0%</tspan>
    </text>

    <text class="caption" x="120" y="220" text-anchor="middle">
      <tspan>CPU Usage</tspan>
    </text>
  </svg>

  <!--
    Gauge: > RAM Usage
  -->
  <svg id="gaugeRAM" percent="0">
    <circle cx="120" cy="120" r="64"></circle>
    <circle cx="120" cy="120" r="64"></circle>

    <text class="value" x="120" y="130" text-anchor="middle">
      <tspan>0%</tspan>
    </text>

    <text class="caption" x="120" y="220" text-anchor="middle">
      <tspan>RAM Usage</tspan>
    </text>
  </svg>

  <!--
    Gauge: > Flash Usage
  -->
  <svg id="gaugeFlash" percent="0">
    <circle cx="120" cy="120" r="64"></circle>
    <circle cx="120" cy="120" r="64"></circle>

    <text class="value" x="120" y="130" text-anchor="middle">
      <tspan>0%</tspan>
    </text>

    <text class="caption" x="120" y="220" text-anchor="middle">
      <tspan>Flash Usage</tspan>
    </text>
  </svg>

  <!--
    Gauge: > Storage
  -->
  <svg id="gaugeStorage" percent="0">
    <circle cx="120" cy="120" r="64"></circle>
    <circle cx="120" cy="120" r="64"></circle>

    <text class="value" x="120" y="130" text-anchor="middle">
      <tspan>0%</tspan>
    </text>

    <text class="caption" x="120" y="220" text-anchor="middle">
      <tspan>Storage Usage</tspan>
    </text>
  </svg>
  <!--/ Animated SVG Gauges -->

</body>
</html>